timeVAE:
  latent_dim: 8
  hidden_layer_sizes:
    - 50
    - 100
    - 200
  reconstruction_wt: 3.0
  batch_size: 16
  use_residual_conn: true
  trend_poly: 0
  custom_seas: null

vae_dense:
  latent_dim: 8
  hidden_layer_sizes:
    - 50
    - 100
    - 200
  reconstruction_wt: 3.0
  batch_size: 16

vae_conv:
  latent_dim: 8
  hidden_layer_sizes:
    - 50
    - 100
    - 200
  reconstruction_wt: 3.0
  batch_size: 16
